---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.1
matrix:
  fast_finish: true
  include:
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=rubocop
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK="syntax lint"
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=metadata_lint
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=release_checks
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
      rvm: 2.1.9
notifications:
  email: false
